In [13]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
filename = "data/2242KANJIFREQUENCYLISTVER.1.1.csv"
df = pd.read_csv(filename)

In [4]:
df.head()

,FORM,Google,KUF,MCD,文化庁,jisho.org,KD,WKFR,AVG FREQ,FREQ (1),FREQ BIG 5
0,一,3,12,30,2,2,12,12,10,9,11
1,二,271,174,85,20,9,284,197,149,151,128
2,仁,1330,1153,1444,1100,1332,1677,805,1263,1242,1254
3,三,278,115,116,30,14,288,122,138,139,121
4,四,614,402,217,103,47,502,438,332,344,312

In [39]:
# FREQ BIG 5

method = "FREQ (1)"

In [40]:
filtered_df = df[df[method] == 4]
filtered_df

Empty DataFrame
Columns: [FORM, Google, KUF, MCD, 文化庁, jisho.org, KD, WKFR, AVG FREQ, FREQ (1), FREQ BIG 5]
Index: []

In [41]:
counts = df[method].value_counts()
print(counts)

FREQ (1)
1105    6
869     6
1484    5
1840    5
842     4
       ..
2859    1
2097    1
3841    1
1906    1
2155    1
Name: count, Length: 1511, dtype: int64

In [45]:
threshold = 1850

result = df[df[method] > threshold].sort_values(by=method, ascending=True).head(5)

result[["FORM", method]]

     FORM  FREQ (1)
1336    敢      1852
861     廻      1853
2031    叔      1853
673     循      1854
1719    呈      1854